### ISSUE TITLE
Allow functions to be passed into the three circles in the bar

### ISSUE THREAD

**Issue by bradarv90** [nitin42/terminal-in-react#1]
It would cool if I could pass either a custom function or there be functions assigned to the three circles in the bar. Perhaps, the red one unmounts the component, yellow shrinks it down and green makes it go full screen.

**Comment by nitin42** [comment]
That's a really good idea ! I will definitely look into this more and will let you know when I've something. Cool ?

**Comment by nitin42** [comment]
@bradarv90 How about this ?

![](https://i.gyazo.com/42b4425dd8fd0d59c2371bcd997a4934.gif)

**Comment by bradarv90** [comment]
I love that!

**Comment by nitin42** [comment]
Thanks !!

**Comment by nitin42** [comment]
@bradarv90  finally made some changes! Check out the readme and update the package if you haven't 😄
