### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by nitin42** [nitin42/terminal-in-react#13]
We need to add more examples covering async handling of commands, advance commands and command pass through!

**Comment by nitin42** [comment]
Added examples [here](https://github.com/nitin42/terminal-in-react/tree/master/examples)

**Comment by tim-soft** [comment]
xterm.js passthrough integration would be super cool

**Comment by CyberCyclone** [comment]
> Added examples [here](https://github.com/nitin42/terminal-in-react/tree/master/examples)

Where's the async examples? The edited files only delay on the main thread. There's no use of async.
