### ISSUE TITLE
Battery widget

### ISSUE THREAD

**Issue by nitin42** [nitin42/terminal-in-react#19]
Display a battery indicator on top left corner of the Bar. This can be achieved by using [battery api](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API)

**Comment by jcgertig** [comment]
I don't know that does not really feel like a feature of a terminal

**Comment by nitin42** [comment]
Well, I use this in my actual terminal!

![](https://i.gyazo.com/2de99f5c17182e7529f362a40ab648ec.gif)

**Comment by nitin42** [comment]
Looks good though!

**Comment by nitin42** [comment]
I was just exploring this https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/system

**Comment by nitin42** [comment]
Or may be, as we will integrate the plugin system soon, we can think about in terms of plugins!

**Comment by jcgertig** [comment]
Yeah as a plugin it makes more sense
