### ISSUE TITLE
contribute style guide needed

### ISSUE THREAD

**Issue by CVarisco** [nitin42/terminal-in-react#3]
Hi @nitin42 !

Cool component 🙂 
Could you provide a contribute guide (how set up the dev env, how to write js, ecc...) ?  Because it would be great contribute to your component.

After that, I will create a PR with a new feature (it is a surprise 🌮 )

**Comment by nitin42** [comment]
Sure @CVarisco ! I am working on it and will upload the guide in an hour.

**Comment by nitin42** [comment]
Btwn @CVarisco are you talking about something like this ?

![](https://i.gyazo.com/42b4425dd8fd0d59c2371bcd997a4934.gif)

**Comment by jcgertig** [comment]
I can make a pr with a eslint config if you would like @nitin42 @CVarisco

**Comment by nitin42** [comment]
Sure ! Go ahead.

**Comment by jcgertig** [comment]
Pr is out #5 but its based off my other pr #4 because I was not paying attention

**Comment by nitin42** [comment]
@CVarisco I've added the guide.

**Comment by nitin42** [comment]
@jcgertig thanks for both the PRs 😄

**Comment by CVarisco** [comment]
Hi @nitin42! 
Thanks to your answer and your work 🙂

However, it would be great if the project has the own dev env (with index.html for example).
Because for the contributor could be annoying to set up the dev env.

What do you think about it ? 
Thanks again 🙂

**Comment by nitin42** [comment]
Can I configure it in the morning ? Its 2:30 AM here and I'm feeling very sleepy. But I will setup everything don't worry !

**Comment by CVarisco** [comment]
Sure! Open source need to be a pleasure not a duty 🙂
Don't worry man 🤙🏻
Thank you for your support!
Good night 🌝

**Comment by nitin42** [comment]
@CVarisco  Go ahead! I've made the changes.
