### ISSUE TITLE
When allowTabs is at false, nothing is shown

### ISSUE THREAD

**Issue by carvallegro** [nitin42/terminal-in-react#30]
I believe that when `allowTabs` is set at false, at least one tab should be shown. 

__with `allowTabs` == true :__
![With allowTabs == true](https://user-images.githubusercontent.com/1234061/28697650-ce033242-7380-11e7-899c-f56dcb3d0250.png)

__with `allowTabs` == false :__
![witj allowTabs == false](https://user-images.githubusercontent.com/1234061/28697664-e7573a22-7380-11e7-80f9-20d495880888.png)

**Comment by jcgertig** [comment]
Thanks for catching that fix has been pushed

**Comment by carvallegro** [comment]
Perfect, awesome reactivity @jcgertig !
