### ISSUE TITLE
about tab

### ISSUE THREAD

**Issue by fansenze** [nitin42/terminal-in-react#32]
### I think we should change the matching rule

> I input 'echo xxx' then I press the Tab. we will find 'xxx' cleared.so I think it's unfriendly.

#### And I think the terminal will have more cue in the future, like: we can see some cue when press Tab after we input 'cd' in iTerm.

**Comment by nitin42** [comment]
umm.. I'm not sure what you said ? Could you elaborate a bit further ? cc @jcgertig

**Comment by fansenze** [comment]
###i mean i want to use TAB to get more infomation
like this:
![wechatimg30](https://user-images.githubusercontent.com/18278456/28964447-5be7087c-793f-11e7-81f6-283dc0e3ab8f.jpeg)
> when i press TAB, you can see many commands with 'l'

others:
> i input 'echo hello', then i press TAB.  try it

**Comment by nitin42** [comment]
Gotcha !! I will add this to my list (for V4). Thanks for the suggestion 😄

**Comment by jcgertig** [comment]
will be out in next release

**Comment by jcgertig** [comment]
new version is out `4.0.0`
