### ISSUE TITLE
Uglify issue with camelcase dependency

### ISSUE THREAD

**Issue by mkaradeniz** [nitin42/terminal-in-react#34]
When using this package with an app bootstrapped with [create-react-app](https://github.com/facebookincubator/create-react-app) the build fails, because [camelcase](https://github.com/sindresorhus/camelcase) will [not use ES5](https://github.com/sindresorhus/ama/issues/446) in their package. Their argument is that they target node and it should be no issue there. 

Since the package's target is cleary the front end would you consider switching to another camelcase library? Maybe the [lodash](https://lodash.com/docs/4.17.4#camelCase) one.

The error:
```
Failed to minify the code from this file:
./node_modules/terminal-in-react/node_modules/camelcase/index.js:4
Read more here: http://bit.ly/2tRViJ9
```

Love the project,

Cheers

**Comment by nitin42** [comment]
Thank you 😀 We know about this issue and it's so cryptic. It's in my to-do and will try to resolve it soon!

**Comment by jcgertig** [comment]
HI @mkaradeniz in our latest release I have switched to `lodash.camelcase` please test to see if the issue is fixed for you

**Comment by mkaradeniz** [comment]
Perfect! Works fine :) Thank you!
