### ISSUE TITLE
Using websockets to pass data?

### ISSUE THREAD

**Issue by MagnumDopus** [nitin42/terminal-in-react#35]
I understand that I can use command passthrough but that is reliant on a transactional system.  If i have a websocket open and i am sending data to a room, and listening for data on a room I am not sure how to push the data I am listening for to the terminal.  

I need some way to bind a listener to a prop within Terminal that will, when receives data, push more lines to the terminal, this may be completely independent of any command, and may happen without user input.

As of right now I cannot figure out a way to do this, any help?

**Comment by jcgertig** [comment]
I would suggest reading up on the plugin api https://github.com/nitin42/terminal-in-react/wiki/Plugins

**Comment by jcgertig** [comment]
Please close this if that satisfies your question

**Comment by MagnumDopus** [comment]
I am not the most clever man but I cannot seem to make it do what I want it to do.  I have created a plugin: 

`import { PluginBase } from 'terminal-in-react';

export default class TerminalPlugin extends PluginBase {
    static displayName() {
        return 'Plugin';
    }
    static version() {
        return '1.0.0';
    }
    constructor(api, config = {}) {
        super(api, config);
        this.api = api;
        this.config = config;
    }

    response(res) {
        this.api.printLine(res);
    }

}`

And I am then loading this plugin: 

`<Terminal
              color="white"
              prompt="white"
              backgroundColor='black'
              barColor='black'
              style={{ fontWeight: "bold", fontSize: "1em" }}
              hideTopBar
              allowTabs={false}
              plugins={[
                  TerminalPlugin
              ]}
              watchConsoleLogging={false}
  />`

and in my component where I am rendering this I am doing this:

`componentDidMount() {
        setInterval(() => {
            TerminalPlugin.response('WOAH A TEST THING!');
        }, 2000);
}`

But instead of that data being pushed to the terminal I am getting this error:

Terminal.jsx:41 Uncaught TypeError: _TerminalPlugin2.default.response is not a function

I am relatively new with classes but I thought I would just be able to access that function.

**Comment by jcgertig** [comment]
A few things. `displayName` and `version` have to be strings not functions.
Each tab instantiates the plugin. Which means it takes the class and calls `new` on it. Class methods are not available in that manner unless they are `static` but plugins are only able to access the api methods in non-static methods. My suggestion is to pass in the socket as a config. This assumes socketio.

```javascript
import { PluginBase } from 'terminal-in-react';
export default class TerminalPlugin extends PluginBase {
    static displayName = 'Plugin';
    static version = '1.0.0';

    constructor(api, config = {}) {
        super(api, config);
        config.socket.on('someEvent', this.response);
    }

    response = (res) => {
        this.api.printLine(res);
    }
}
```

Used in a component that connects to the socket and has it available

```jsx
<Terminal
  color="white"
  prompt="white"
  backgroundColor='black'
  barColor='black'
  style={{ fontWeight: "bold", fontSize: "1em" }}
  hideTopBar
  allowTabs={false}
  plugins={[{
    class: TerminalPlugin,
    config: {
      socket: this.socket
    }
  }]}
  watchConsoleLogging={false}
/>
```

**Comment by MagnumDopus** [comment]
You sir are a genius, I believe this should do it!  Real quick, and I completely understand that this is not really the place for this question, so feel free to disregard and close, but I am not using the stage-0 babel presets so I cannot do class property transforms, so writing static displayName = "Plugin"; throws an error during webpack.  I thought the way to get around this was writing it as I did above, but clearly that is wrong, is there a way to write it appropriately without using the transform?

**Comment by jcgertig** [comment]
Yes if you are not using stage-0 or stage-1 i believe, then you can add static attributes like so.
 ```javascript
import { PluginBase } from 'terminal-in-react';
class TerminalPlugin extends PluginBase {
    constructor(api, config = {}) {
        super(api, config);
        config.socket.on('someEvent', this.response);
    }

    response = (res) => {
        this.api.printLine(res);
    }
}

TerminalPlugin.displayName = 'Plugin';
TerminalPlugin.version = '1.0.0';

export default TerminalPlugin;
```

**Comment by jcgertig** [comment]
If this is working for you now please close this issue :)

**Comment by MagnumDopus** [comment]
Yes, sorry for the delayed response!  Thank you for helping clarify my noob misunderstandings, thank you!
