### ISSUE TITLE
Way to get onChange of terminal? 

### ISSUE THREAD

**Issue by MagnumDopus** [nitin42/terminal-in-react#37]
I am scratching my head on this one, I don't want to get the full command on enter, I instead want to bind to every change that occurs when typing in the terminal (we use a fully simulated pty backend, so we must send a character at a time).

It is not clear if this is possible in the current release, am I missing something?

**Comment by jcgertig** [comment]
Why would you need each change can you give me more details as to the use case. Why would your simulated pty backend need each character?

**Comment by MagnumDopus** [comment]
Unfortunately I am merely the front end monger, but the idea is basically it simulates a total pty enviornment and every keystroke is sent to the backend, it isn't really sent a "command" it is sent a series of characters and when it is then also fed an enter key it acts as a terminal would and ingests what it has as a shell command.

**Comment by jcgertig** [comment]
Not currently its something I could add but I cant not promise to get to it before this weekend. But I would be happy to review a pr that adds it.

**Comment by MagnumDopus** [comment]
I may look into that if I have the cycles, though I may be able to jerry-rig it to work as is.  On a related but different note, I cannot figure out how to disable the built in commands completely?  I don't want help to do anything client side, since there will be a serverside help method pushed through the pty.

**Comment by jcgertig** [comment]
the best way to override the built in commands is to do just that. Pass into the commands props the commands you want to disable ie: 
```jsx
commands={{
  help: () => {}
}}
```
the names of the built in commands are 'show', 'echo', 'edit-line', 'clear', 'help'. The two I would caution against overriding would be 'edit-line' and 'clear'. The others are much less important. For instance the pseudo filesystem plugin overrides 'echo' to extend it.

**Comment by MagnumDopus** [comment]
The problem is, while that does override the normal behavior of 'help', it still intercepts the command and now commandPassThrough is still not being called when 'help' is entered.

**Comment by jcgertig** [comment]
try this
```
commands={{
  help: undefined
}}
```

**Comment by MagnumDopus** [comment]
unfortunately that throws the following error:

`Terminal.js:1 Uncaught TypeError: i.method is not a function`

**Comment by jcgertig** [comment]
okay 3.5.1 should fix that

**Comment by MagnumDopus** [comment]
Alright thank you so much, I'll keep my eyes peeled.  I'm going to attempt to implement an onchange bind somewhere in the code, admittedly this will be my first github contribution so hopefully I don't bungle it too badly!

**Comment by MagnumDopus** [comment]
I have submitted PR #40 .  As this is my first github/open-source contribution please feel free to tell me how stupid or wrong anything I did was.  I don't mind evisceration if it means I learn.
