### ISSUE TITLE
Is there a way to replace getNote?

### ISSUE THREAD

**Issue by pigletfly** [nitin42/terminal-in-react#39]
This is a fabulous component.I find if Terminal is not shown,this default action is ```getNote```,so is there a way to replace ```getNote```, maybe pass through props?Actually,what I want is a ```visible``` props to handle Terminal visibility manually.

**Comment by nitin42** [comment]
cc @jcgertig !

**Comment by jcgertig** [comment]
you can override the actions that the menu icons perform

**Comment by jcgertig** [comment]
@pigletfly 
```
<Terminal
  actionHandlers={{
    handleClose: (toggleClose) => {
      // do something on close
      toggleClose();
    },
    handleMaximise: (toggleMaximise) => {
      // do something on maximise
      toggleMaximise();
    }
  }}
/>
```
does this solve your issue?

**Comment by pigletfly** [comment]
cool
