### ISSUE TITLE
Is there a way to capture ALL commands?

### ISSUE THREAD

**Issue by juanmanuelarias** [nitin42/terminal-in-react#42]
I'd like to capture all commands that are passed to the Terminal, is that possible?

Cheers,

**Comment by jcgertig** [comment]
Unfortunately no. Just ones that are not handled via the
commandPassThrough. Adding a handler that just passes out any input would
be easy enough and we would be open to a pr.

**Comment by jcgertig** [comment]
There will be in the next release. It will be the prop: `commandWasRun`

**Comment by jcgertig** [comment]
new version is out `4.0.0`
