### ISSUE TITLE
issue with  dependanices

### ISSUE THREAD

**Issue by id0Sch** [nitin42/terminal-in-react#43]
Hi,
I'm getting an error when trying to use the module.
I have the most basic usage straight from the docs.
I installed via yarn (version 1.3.2)

can you please assist ? 
thanks 

``` javascript
  render() {
    return <Terminal
      color='green'
      backgroundColor='black'
      barColor='black'
      style={{fontWeight: "bold", fontSize: "1em"}}
      commands={{
      }}
      descriptions={{
      }}
      msg='You can write anything here. Example - Hello! My name is Foo and I like Bar.'
    />
  }
```
``` json
"dependencies": {
    "autosuggest-highlight": "^3.1.1",
    "brace": "^0.10.0",
    "classnames": "^2.2.5",
    "lodash": "^4.17.4",
    "material-ui": "^1.0.0-beta.22",
    "material-ui-icons": "^1.0.0-beta.17",
    "prop-types": "^15.6.0",
    "react": "^16.0.0",
    "react-ace": "^5.4.0",
    "react-autosuggest": "^9.3.2",
    "react-dom": "^16.0.0",
    "react-router-dom": "^4.2.2",
    "react-sortable-hoc": "^0.6.8",
    "react-tap-event-plugin": "^3.0.2",
    "terminal-in-react": "3.5.0"
  },
```
![image](https://user-images.githubusercontent.com/5864772/33449686-2bd0759e-d612-11e7-9721-dcaef3dd5ce2.png)

**Comment by id0Sch** [comment]
so I got it working by adding the deps manually but now I have an issue with the styling.
It seems as if the styling is not applied to the components properly 

![image](https://user-images.githubusercontent.com/5864772/33451202-f9ecff84-d616-11e7-9e33-02a6e4b0cd3d.png)

**Comment by nitin42** [comment]
Hmm... May be @jcgertig can help you! He refactored the codebase and also worked on styling.

**Comment by jcgertig** [comment]
new version is out `4.0.0`
