### ISSUE TITLE
Unable to install package 15.6.2

### ISSUE THREAD

**Issue by thachp** [nitin42/terminal-in-react#45]
When I ran npm install I got the following error.

```npm install terminal-in-react --save-dev```

![image](https://user-images.githubusercontent.com/1495371/33527005-2199c952-d7fe-11e7-91d8-881b941f7316.png)

OSX Sierra
NPM 4.1.2
React 15.6.2

**Comment by nitin42** [comment]
I'll resolve this issue soon. Busy with college exams!

**Comment by thachp** [comment]
@nitin42 awesome! thanks for your help.

**Comment by nitin42** [comment]
Started working though but haven't pushed anything so far 😅

**Comment by Ashisacat** [comment]
Any updated on this?

**Comment by nitin42** [comment]
Fixed and released `terminal-in-react@3.5.2`
