### ISSUE TITLE
Easier way to run commands from external component

### ISSUE THREAD

**Issue by rob10e** [nitin42/terminal-in-react#46]
I was wondering if there is an easier way to run commands from an external component?

Currently I have a button that provides the user the option to clear the terminal without having to type in the command. The code I am using to perform this is:

```javascript
    this.instance.runCommand(this.instance.getChildContext().instances[0].instance, 'clear');
```

I think something more along the lines of: 

```javascript
    this.instance.runCommand('clear');
```

or
```javascript
    this.instance.runCommand('clear', this.instance.currentTab);
```

where `this.instance` is a `ref` to the `<Terminal />` instance.

**Comment by jcgertig** [comment]
`runCommandOnActive` will be added to the next version

`runCommandOnActive('clear')`

**Comment by jcgertig** [comment]
new version is out `4.0.0`

**Comment by mkskitka** [comment]
Could someone give an example of how to use this? The function is not exposed as a prop so I have no idea how to access it. This also isn't included in the readme

**Comment by misolo** [comment]
@mkskitka,  Here an exapmle: 

Define `ref`:
```
 <Terminal
        ref={(terminal) => { this.terminalObj = terminal; }}
        commands={{
            'my-cmd' : (args, print, runCommand) => {
                 print('hello  my-cmd !');
             }
         }}
   />
```

Use the ref :
`this.terminalObj.runCommandOnActive('my-cmd')`
