### ISSUE TITLE
Got a Element type is invalid error.

### ISSUE THREAD

**Issue by leuction** [nitin42/terminal-in-react#47]
Hello! Thank you for your great project.

I try to create a terminal with the demo code posted on README.md, and I got an error with the following:

<img width="663" alt="screen shot 2018-01-24 at 3 27 12 pm" src="https://user-images.githubusercontent.com/8056270/35355383-251935fe-011b-11e8-926f-3470b1aa9be2.png">

Thank you for your help.

**Comment by Coriou** [comment]
Getting this issue too, using Create React App, using the example and nothing else (React 16.2)

**Comment by mgebeily** [comment]
Also getting this error.

**Comment by jcgertig** [comment]
Yeah same I was planning on doing a once over and working on upgrades

**Comment by jcgertig** [comment]
Will be fixed in next release

**Comment by jcgertig** [comment]
new version is out `4.0.0`
