### ISSUE TITLE
Color changes once commands get executed.

### ISSUE THREAD

**Issue by GnaneshKunal** [nitin42/terminal-in-react#50]
All the commands turn to green once they get executed. Like this:

![terminal](https://user-images.githubusercontent.com/20211167/36259065-fb1da7c0-1282-11e8-8150-261a6b58020c.png)
I've even tried setting my color prop to black but no use.
```jsx
<Terminal
    color='black'
    backgroundColor='white'
    prompt="black"
/>
```
I've then tried creating a new property named `historyColor` which holds the color value of previous commands and added it to the React component.
```js

// src/js/components/Terminal
const theme = {
      ...
      historyColor: this.props.historyColor
    };

// src/js/components
export const TerminalPropTypes = {
      ...
      historyColor: PropTypes.string,
}
export const TerminalDefaultProps = {
        historyColor: 'black',
}

// src/js/components/Content/styled-elements.js
const outputLineStyle = `
      ...
      color: ${props => props.theme.historyColor};
`;
```
It still doesn't work.

But what caught me was, `outputLineStyle.color`(CSS) was the variable that was holding the color value. Modifying the value changes the color.
So removing that label makes the container to use `Terminal.color` prop as it's value.
So, Is it a bug(and must be removed) or Is there a way to modify the color of previous commands?

**Comment by jcgertig** [comment]
release 4.1.1 now uses the color attribute

**Comment by jcgertig** [comment]
4.2.1 now also adds outputColor prop
