### ISSUE TITLE
Server Side Rendering: window is not defined error

### ISSUE THREAD

**Issue by tim-soft** [nitin42/terminal-in-react#6]
Hey guys, this component is really cool!

Are there any plans to make this component work with SSR?

I am guessing this error is alluding to the server not having a window size
```
ReferenceError: window is not defined
```

**Comment by nitin42** [comment]
@tim-soft thanks for reporting the error! Can you share your code snippet ?

**Comment by nitin42** [comment]
Because its just a component after all and not a library, so there is no need of explicit instructions for SSR. May be there is an error in your codebase where you are performing SSR.

**Comment by tim-soft** [comment]
I tried a copy/paste from the readme into one of my SSR apps. 

There _are_ ways around this on my end, such as disabling SSR for a specific page, but I believe this is a problem better solved on the component/lib side.

An easy way to test is to clone something like [kriasoft/react-starter-kit](https://github.com/kriasoft/react-starter-kit) and pop the terminal component onto the homepage

```javascript
<div>
    <Terminal
        color="green"
        backgroundColor="black"
        barColor="black"
        style={{ fontWeight: 'bold', fontSize: '1em' }}
        commands={{
          'open-google': () => window.open("https://www.google.com/", "_blank"),
          showmsg: this.showMsg,
          popup: () => alert("Terminal in React")
        }}
        description={{
          'open-google': 'opens google.com',
          showmsg: 'shows a message',
          alert: 'alert', popup: 'alert'
        }}
        msg="You can write anything here. Example - Hello! My name is Foo and I like Bar."
    />
</div>
```

**Comment by nitin42** [comment]
Yes I also had this same error when I was using a client-side lib in one of my projects. But I've published a new version of the component on npm `1.1.0`. Try it again and let me know.

**Comment by nitin42** [comment]
This error is mostly caused by the client side lib (because window object is only available on browser). Seems like I'll have to add SSR support !

**Comment by nitin42** [comment]
I got this!

```
window.open("https://www.google.com/", "_blank")
```

Did you see that ? `window` object ? It's only available on client side.

**Comment by nitin42** [comment]
If you want to keep this example, something like this should work! 

```html
"<script>window.open('" +url+ "');</script>")
```

**Comment by tim-soft** [comment]
Do'h!

That fixed this problem, but I appear to be having some silent issue that is crashing my app. Although this is probably due to my funky webpack config

I'll report back when I get it running, thank you!
