### ISSUE TITLE
How can I add a prompt command instead of running a command?

### ISSUE THREAD

**Issue by Blezzoh** [nitin42/terminal-in-react#73]
Hi I wanted to ask if there is a feature where running one command will prompt another one.
For example:
//running the command 'address' prompt another command but does run it until you press enter
'>address
'>enter address one: somwhere st 
'>enter city: somecity
'>enter state: someState
....

thanks

**Comment by manurg** [comment]
Hi, i had to get user input as well and worked around it with custom commands. In my case i added a `set` command and checked for following passed arguments. I think a cleaner solution would be writing a custom plugin.

**Comment by jcgertig** [comment]
Yes a plugin is more suited to the use case you have. I will add a "read" command to the todos

**Comment by Blezzoh** [comment]
Thank you guys, I will look into a way of creating a plugin.
