### ISSUE TITLE
Listen for Ctrl + l for 'clear'

### ISSUE THREAD

**Issue by lasseborly** [nitin42/terminal-in-react#8]
I'll gladly make the PR if this is a feature that is wished for.

**Comment by jcgertig** [comment]
please do and do cmd + k for mac support

**Comment by jcgertig** [comment]
The best way to approach this would be a way to define hot keys and the name of the command they call. I can add that if you dont want to

**Comment by nitin42** [comment]
Great !! That will be a cool feature. 👍

**Comment by nitin42** [comment]
@jcgertig can you elaborate a bit further ?

**Comment by nitin42** [comment]
Also @lasseborly go ahead and make the PR!

**Comment by jcgertig** [comment]
something like 
```javascript
hotkeys={{
  'ctrl + l': 'clear',
  'cmd + k': 'clear',
}}
```

then the code can build up a string of inputs
and filter out options of commands based on matches.
like

```javascript
const keyMaps = Object.keys(hotkeys);
const keys = keyMaps.map(key => key.replace(/\s/g, '').split('+')).map((keyset, index) => ({ keyset, index }));
const options = keys.filter(item => {
  if (item.keyset.length >= inputs.length) {
    return isEqual(item.keyset.slice(0, inputs.length), inputs); // 'lodash.isequal'
  }
  return false;
});
if (options.length === 0) {
  // should restart key checking
}
if (options.length === 1 && options[0].length === inputs.length) {
  // run hotkeys[keyMaps[options[0].index]]
} else {
 // continue gathering keys
}

```

**Comment by jcgertig** [comment]
@lasseborly  I would suggest you try [whatkey](https://www.npmjs.com/package/whatkey) for getting key names

**Comment by nitin42** [comment]
Looks good 👍 . Do you want to try this ? Or you've already started 😄  ?

**Comment by jcgertig** [comment]
Have not started but Ive built similar things and the package Ive linked shows

**Comment by nitin42** [comment]
Currently I am busy with #1 and improving the documentation. You can start working on this and then we can review it later. Cool ?

**Comment by lasseborly** [comment]
I'll begin work on this tomorrow if that is okay with you guys. I'll prob. come  by for getting some feedback and getting some questions answered. Thanks @jcgertig and @nitin42

**Comment by nitin42** [comment]
Sure 👍

**Comment by nitin42** [comment]
Don't forget to do a `git pull` before you start 😅

**Comment by lasseborly** [comment]
Yeeessss.. Of course.

**Comment by nitin42** [comment]
Hehe!

**Comment by jcgertig** [comment]
hows it commming @lasseborly

**Comment by lasseborly** [comment]
I did not get the time today. Feel free :)

**Comment by jcgertig** [comment]
This has been done will close once its released
